export const Pahts = {
    methodasisst: 'methodasisst',
    services: 'services',
    media: 'media', 
    aboutus: 'aboutu',
    staff: 'staff',
    contacts: 'contacts',
    project: 'projects',
    reguldoc: 'reguldocs',
    hrental: 'hrental',
    excursion: 'excursions',
    tutorial: 'tutorials',
    udm_new: 'udm_news',
    fun_new: 'fun_news',
    fair_new: 'fair_news',
    paper: 'papers',
    video_clip: 'video_clips',
    video_course: 'video_courses',
    video_webinar: 'video_webinars',
    foto: 'fotos',
    audio: 'audios',
    admin: 'admin',
    postingspost: 'new_posting_post'
}